import { ApiError } from './api'

/**
 * What the owner is told, in the language the interface is in. The server answers in English
 * and keeps doing so — its messages are for the log and the test suite, and its vocabulary is
 * the error code, not the sentence.
 *
 * Only a code is ever looked up here. A server message is never shown, including one forwarded
 * from the engine or generated by schema validation, because those are written for whoever
 * maintains the system rather than for whoever is standing in a doorway with a guest.
 */
const COPY: Record<string, string> = {
  offline: 'Нет связи с сервером. Проверьте интернет.',
  unauthorized: 'Сессия истекла. Войдите снова.',
  invalid_phone: 'Укажите номер с кодом страны — например, +375 29 123 45 67.',
  validation_error: 'Проверьте, что все поля заполнены правильно.',
  not_found: 'Запись не найдена — возможно, её уже удалили.',
  conflict: 'Эти данные только что изменились. Обновите страницу и попробуйте снова.',
  bad_request: 'Сервер не принял запрос.',
  internal_error: 'Что-то пошло не так на сервере. Попробуйте ещё раз.',

  // The engine could not be reached, or answered something that is not the owner's doing.
  engine_unreachable: 'Движок бронирования не отвечает. Попробуйте ещё раз через минуту.',
  engine_rejected_our_key: 'Движок бронирования отклонил запрос. Это ошибка настройки, не ваша.',

  // The engine's own vocabulary for things the owner did and can undo.
  slot_unavailable: 'Эти ночи уже заняты.',
  outside_schedule: 'Эти даты вне расписания дома.',
  resource_inactive: 'Дом сейчас закрыт для брони.',
  invalid_state_transition: 'С этой бронью такое действие уже недоступно.',
  hold_expired: 'Бронь не была подтверждена вовремя. Заведите её заново.',
  invalid_interval: 'Проверьте даты заезда и выезда.',
}

const GENERIC = 'Что-то пошло не так. Попробуйте ещё раз.'

/**
 * `fallback` says what failed, for a code with no copy of its own — "could not save the
 * booking" reads better than the generic line when the screen knows what was being attempted.
 */
export function messageFor(cause: unknown, fallback: string = GENERIC): string {
  if (cause instanceof ApiError) return COPY[cause.code] ?? fallback
  return fallback
}
